<?xml version="1.0" encoding="utf-8"?><Database Name="Exercise" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\Exercise.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ExConnString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.emp_info" Member="emp_infos">
    <Type Name="emp_info">
      <Column Name="eid" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="enmae" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="designation" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="salary" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>